### ISSUE TITLE
大佬我问一下如何才能进入 我的是500

### ISSUE THREAD

**Issue by pythonaih** [yuemiao-web/yuemiao_frontend#1]
curl http://localhost:5000/
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>

npm install
yarn serve 

端口启动起来的 5000

如何才能进去

**Comment by coder-xiaotian** [comment]
> curl http://localhost:5000/
> 
> <title>Error</title>
> Cannot GET /
> npm install yarn serve
> 
> 端口启动起来的 5000
> 
> 如何才能进去
页面看不到吗？

**Comment by AnTi-anti** [comment]
我也是，一样的问题

**Comment by pythonaih** [comment]
是的没有页面

**Comment by coder-xiaotian** [comment]
> 是的没有页面
> 

应该是yarn dev开发环境启动，不好意思写错了😂
